### ISSUE TITLE
Umbrella issue: implement the chat feature found in https://www.instagram.com/direct/inbox/ 

### ISSUE THREAD

**Issue by alshakero** [alshakerM/my-instagram#9]
For now let's make the messages read-only to make it easier. 

#### Here are the features we need:

- [x] Generate data using [mockaroo](https://www.mockaroo.com/) for messages. We can do that together.
- [x] Create a list of users with 1) username 2) thumbnail 3) and truncated last message 4) relative time. Each item in the list should be a component called "MessageListItem".
- [x] Before you click a message, you should see a nice UI indicating that you can click, [like this](https://user-images.githubusercontent.com/17054134/141786714-d04b5284-098b-429f-b7db-702dcbb571ed.png).
- [x] When you click a message item, the chat opens up on the right side. And you see messages from yourself and the other user.
- [ ] In the bottom of the right side, there should be an input field similar to the one under the posts.

Each one of these points requires a separate PR.

**Comment by alshakero** [comment]
Can be closed now.

**Comment by alshakerM** [comment]
Fixed in #31
